import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import PptxGenJS from 'pptxgenjs';

export const exportToPDF = async (elementId, fileName = 'pitch.pdf') => {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('Element not found');
    return;
  }

  // Add a temporary loading state or class if needed, or clone the element to modify styles for PDF
  // For now, we capture as is.

  try {
    const canvas = await html2canvas(element, {
      scale: 2, // Improve quality
      useCORS: true,
      logging: false,
      backgroundColor: '#0f172a', // Use dark background to match theme, or white if preferred
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight
    });

    const imgData = canvas.toDataURL('image/png');
    
    // A4 dimensions
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgWidth = 210;
    const pageHeight = 297; 
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(fileName);
  } catch (error) {
    console.error('Error exporting PDF:', error);
  }
};

export const exportToPPTX = (data) => {
  if (!data) return;

  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_16x9';
  
  // Define a dark theme
  const slideBg = { color: '111827' };
  const titleColor = 'FFFFFF';
  const bodyColor = 'E5E7EB';

  // HELPER: Add master slide definition if needed, or just style each slide
  
  // -- SLIDE 1: Title Slide --
  const slide1 = pptx.addSlide();
  slide1.background = slideBg;
  
  slide1.addText(data.name || 'Startup Name', {
    x: 0.5, y: 2, w: '90%',
    fontSize: 44, color: titleColor, bold: true, align: 'center',
    glow: { size: 5, opacity: 0.3, color: '6366F1' } // subtle glow
  });
  
  slide1.addText(data.tagline || '', {
    x: 1, y: 3.5, w: '80%',
    fontSize: 24, color: '9CA3AF', align: 'center', italic: true
  });

  slide1.addText('Generated by PitchCraft', {
    x: 0, y: 6.5, w: '100%',
    fontSize: 12, color: '4B5563', align: 'center'
  });

  // -- SLIDE 2: Elevator Pitch --
  const slide2 = pptx.addSlide();
  slide2.background = slideBg;
  slide2.addText('Elevator Pitch', { x: 0.5, y: 0.5, fontSize: 32, color: 'F472B6', bold: true });
  
  slide2.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: 'F472B6' }); // Underline
  
  slide2.addText(`"${data.elevator_pitch || ''}"`, {
    x: 1, y: 2, w: '80%',
    fontSize: 24, color: bodyColor, italic: true, align: 'center'
  });

  // -- SLIDE 3: Problem --
  const slide3 = pptx.addSlide();
  slide3.background = slideBg;
  slide3.addText('The Problem', { x: 0.5, y: 0.5, fontSize: 32, color: 'EF4444', bold: true });
  slide3.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: 'EF4444' });

  slide3.addText(data.problem || 'No problem description provided.', {
    x: 0.5, y: 2, w: '90%',
    fontSize: 18, color: bodyColor, bullet: true, lineSpacing: 32
  });

  // -- SLIDE 4: Solution --
  const slide4 = pptx.addSlide();
  slide4.background = slideBg;
  slide4.addText('The Solution', { x: 0.5, y: 0.5, fontSize: 32, color: '10B981', bold: true });
  slide4.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: '10B981' });

  slide4.addText(data.solution || 'No solution description provided.', {
    x: 0.5, y: 2, w: '90%',
    fontSize: 18, color: bodyColor, bullet: true, lineSpacing: 32
  });

  // -- SLIDE 5: Unique Value Proposition --
  const slide5 = pptx.addSlide();
  slide5.background = slideBg;
  slide5.addText('Unique Value Proposition', { x: 0.5, y: 0.5, fontSize: 32, color: 'F59E0B', bold: true });
  slide5.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: 'F59E0B' });

  slide5.addText(data.unique_value_proposition || '', {
    x: 0.5, y: 2.5, w: '90%',
    fontSize: 24, color: bodyColor, align: 'center', bold: true
  });

  // -- SLIDE 6: Target Audience --
  const slide6 = pptx.addSlide();
  slide6.background = slideBg;
  slide6.addText('Target Audience', { x: 0.5, y: 0.5, fontSize: 32, color: '3B82F6', bold: true });
  slide6.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: '3B82F6' });

  slide6.addText(data.target_audience?.description || '', {
    x: 0.5, y: 2, w: '90%', h: 1.5,
    fontSize: 16, color: bodyColor
  });

  if (data.target_audience?.segments && data.target_audience.segments.length > 0) {
      slide6.addText('Key Segments:', { x: 0.5, y: 4, fontSize: 18, color: '9CA3AF', bold: true });
      
      const segments = data.target_audience.segments.map(s => s).join('\n');
      slide6.addText(segments, {
        x: 0.5, y: 4.5, w: '90%',
        fontSize: 16, color: bodyColor, bullet: true
      });
  }

  // -- SLIDE 7: Market & Business Model --
  const slide7 = pptx.addSlide();
  slide7.background = slideBg;
  slide7.addText('Market & Business Model', { x: 0.5, y: 0.5, fontSize: 32, color: '8B5CF6', bold: true });
  slide7.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.5, w: 12.33, h: 0.1, fill: '8B5CF6' });

  slide7.addText('Industry:', { x: 0.5, y: 2.5, w: 3, fontSize: 18, color: '9CA3AF', bold: true });
  slide7.addText(data.industry || 'N/A', { x: 3.5, y: 2.5, w: 8, fontSize: 18, color: bodyColor });

  slide7.addText('Business Model:', { x: 0.5, y: 3.5, w: 3, fontSize: 18, color: '9CA3AF', bold: true });
  slide7.addText('B2B SaaS (Example)', { x: 3.5, y: 3.5, w: 8, fontSize: 18, color: bodyColor }); // Assuming generic or extracting if available

  pptx.writeFile({ fileName: `${(data.name || 'pitch').replace(/[^a-z0-9]/gi, '_').toLowerCase()}_presentation.pptx` });
};
